version: '3.5'
services:
  config:
    container_name: 'ecommerce_cart_rest_api_config'
    image: 'composer:2.1.5'
    volumes:
      - './:/app'
    command: composer install --ignore-platform-reqs

  backend:
    container_name: 'ecommerce_cart_rest_api_backend'
    image: raphaelbatagini/apache-php-grpc:8.0.2
    ports:
      - '80:80'
    volumes:
      - './:/var/www/html'
    depends_on:
      config:
        condition: service_completed_successfully

  discount-service:
    container_name: 'ecommerce_cart_rest_api_discount_service'
    image: hashorg/hash-mock-discount-service
    ports:
      - '50051:50051'

  tests:
    container_name: 'ecommerce_cart_rest_api_tests'
    image: raphaelbatagini/apache-php-grpc:8.0.2
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit tests
    depends_on:
      config:
        condition: service_completed_successfully
