version: '3.5'
services:
  config:
    container_name: '${APP_NAME}_config'
    image: 'composer:2.1.5'
    volumes:
      - './:/app'
    command: composer install --ignore-platform-reqs

  api:
    container_name: '${APP_NAME}_api'
    build: .
    ports:
      - '80:80'
    volumes:
      - './:/var/www/html'
    depends_on:
      config:
        condition: service_completed_successfully

  discount-service:
    container_name: '${APP_NAME}_discount_service'
    image: hashorg/hash-mock-discount-service
    ports:
      - '50051:50051'

  phpunit:
    container_name: '${APP_NAME}_tests'
    build: .
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
