version: '3.5'
services:
  config:
    container_name: 'http_ecommerce_cart_api_config'
    image: 'composer:2.1.5'
    volumes:
      - './:/app'
    command: composer install --ignore-platform-reqs

  api:
    container_name: 'http_ecommerce_cart_api_api'
    build: .
    ports:
      - '80:80'
    volumes:
      - './:/var/www/html'
    depends_on:
      config:
        condition: service_completed_successfully

  discount-service:
    container_name: 'http_ecommerce_cart_api_discount_service'
    image: hashorg/hash-mock-discount-service
    ports:
      - '50051:50051'

  tests:
    container_name: 'http_ecommerce_cart_api_tests'
    build: Dockerfile.tests
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit tests
