<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discount.proto

namespace Discount;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * productID used to represent a product. Ilustrative only.
 *
 * Generated from protobuf message <code>discount.GetDiscountRequest</code>
 */
class GetDiscountRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 productID = 1;</code>
     */
    protected $productID = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $productID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Discount::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 productID = 1;</code>
     * @return int
     */
    public function getProductID()
    {
        return $this->productID;
    }

    /**
     * Generated from protobuf field <code>int32 productID = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProductID($var)
    {
        GPBUtil::checkInt32($var);
        $this->productID = $var;

        return $this;
    }

}

