<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discount.proto

namespace Discount;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The discount percentage is a fixed value.
 *
 * Generated from protobuf message <code>discount.GetDiscountResponse</code>
 */
class GetDiscountResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float percentage = 1;</code>
     */
    protected $percentage = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $percentage
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Discount::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float percentage = 1;</code>
     * @return float
     */
    public function getPercentage()
    {
        return $this->percentage;
    }

    /**
     * Generated from protobuf field <code>float percentage = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setPercentage($var)
    {
        GPBUtil::checkFloat($var);
        $this->percentage = $var;

        return $this;
    }

}

